import numpy 
import json

#string ID
#string Name
#string preference
# 1d array diet 6l
# 1d array allergy 10 length
#array of stringsexclusions
 
class Group:
    groupPref
    groupDiet
    groupAllergies
    groupExclusions
    groupMembersID
    groupMembersName
    
    #Initializes the init for the group class that is generated by grouper
    def __init__(self, groupPref, groupDiet, groupAllergies, groupExclusions, groupMembersID, groupMembersName):
        self.groupPref = groupPref
        self.groupDiet = groupDiet
        self.groupAllergies = groupAllergies
        self.groupExclusions = groupExclusions
        self.groupMembersID = groupMembersID
        self.groupMembersName = groupMembersName
    
    #Returns the list of preferences for a group
    @property
    def pref(self):
        return self.groupPref
        
    @pref.setter
    def pref(self, pref):
        self._pref = pref
        
    @pref.deleter
    def pref(self):
        del self.pref
    
    #Returns the List of diets the group adheres to
    def getDiet(self):
        return self.groupDiet
    
    #Returns the list of allergies group members adhere to
    def getAllergies(self):
        return self.groupAllergies
    
    #Returns the list of food exclusions for the group
    def getExlusions(self):
        return self.groupExclusions

    #Returns the list of facebook IDs for the group
    def getIDs(self):
        return self.groupMembersID
    
    #Returns the List of names for the group
    def getNames(self):
        return self.groupMembersName
 
