import numpy 
import json

#string ID
#string Name
#string preference
# 1d array diet 6l
# 1d array allergy 10 length
#array of stringsexclusions
 
class Group:
    '''
    groupPref
    groupDiet
    groupAllergies
    groupExclusions
    groupMembersID
    groupMembersName
    '''
    #Initializes the init for the group class that is generated by grouper
    def __init__(self, groupPref, groupDiet, groupAllergies, groupExclusions, groupMembersID, groupMembersName):
        self._groupPref = groupPref
        self._groupDiet = groupDiet
        self._groupAllergies = groupAllergies
        self._groupExclusions = groupExclusions
        self._groupMembersID = groupMembersID
        self._groupMembersName = groupMembersName
    
    ##########################
    #Returns the list of preferences for a group
    @property
    def pref(self):
        return self._groupPref
        
    @pref.setter
    def pref(self, pref):
        self._groupPref = pref
        
    @pref.deleter
    def pref(self):
        del self.groupPref
        
    ##########################
    #Returns the List of diets the group adheres to
    @property
    def diet(self):
        return self._groupDiet
    
    @diet.setter
    def diet(self, diet):
        self._groupdiet = diet
        
    @diet.deleter
    def diet(self):
        del self.groupDiet
        
    ##########################
    #Returns the list of allergies group members adhere to
    @property
    def allergies(self):
        return self._groupAllergies
        
    @allergies.setter
    def allergies(self, allergies):
        self._groupAllergies = allergies
        
    @allergies.deleter
    def allergies(self):
        del self.groupAllergies
        
    ##########################
    #Returns the list of food exclusions for the group
    @property
    def exclusions(self):
        return self._groupExclusions
        
    @exclusions.setter
    def exclustions(self, exclusions):
        self._groupExclusions = exclusions
        
    @exclusions.deleter
    def exclusions(self):
        del self.exclusions

    ##########################
    #Returns the list of facebook IDs for the group
    @property
    def IDs(self):
        return self._groupMembersID
        
    @IDs.setter
    def IDs(self, ids):
        self._groupMembersID = ids
        
    @IDs.deleter
    def IDs(self):
        del self.groupMembersID
    
    ##########################
    #Returns the List of names for the group
    @property
    def names(self):
        return self._groupMembersName
        
    @names.setter
    def names(self, names):
        self._groupMembersName = names
        
    @names.deleter
    def names(self):
        del self.groupMembersName
 
